### ISSUE TITLE
I can't get to use it, how to?

### ISSUE THREAD

**Issue by gemalaputri** [tsambora/react-atomic-pattern#1]
I try to playing this also, could you please give some guide here?

**Comment by tsambora** [comment]
Sorry I haven't put a readme for this repo. I'll write it thoroughly ASAP. In a meantime you can run this project by:

* downloading the project
* open your terminal, then:

To run the Storybook catalog
* move to the pattern lib directory
* run `npm install`
* run `npm run storybook`

The component catalog will be available in `localhost:6006`

To run the sample project
* in the pattern lib directory, run `npm link`
* move to the react app directory and run `npm link atomic-pattern-library`
* run `npm install` in the react app directory
* run `npm run dev` in the react app directory

The sample react app will be available in `localhost:8080`

Hope this helps.

**Comment by gemalaputri** [comment]
got it, thanks a lot!
